AVR2025: IEEE 802.15.4 MAC Reference Manual
Microcontroller Wireless Solutions
pal.c File Reference
General PAL functions for AVR 8-Bit MCUs.
Functions
static void mcu_clock_init (void)
void pal_alert (void)
retval_t pal_init (void)
retval_t pal_ps_get (ps_type_t ps_type, uint16_t start_addr, uint16_t length, void *value)
retval_t pal_ps_set (uint16_t start_addr, uint16_t length, void *value)
void pal_task (void)
Variables
volatile uint16_t sys_time
Detailed Description
General PAL functions for AVR 8-Bit MCUs.
This file implements generic PAL function and performs USB related handling if required for AVR 8-Bit MCUs.
Id:
pal.c 21606 2010-04-14 14:09:54Z uwalter
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Definition in file pal.c.
Function Documentation
static void mcu_clock_init (void) [static]
Initialize the system clock.
This function sets the system clock by enabling the internal RC oscillator with the proper prescaler (if available). Ensure that CKDIV8 fuse does not affect the system clock prescaler.
Definition at line 222 of file pal.c.
References ENTER_CRITICAL_REGION, and LEAVE_CRITICAL_REGION.
Referenced by pal_init().
void pal_alert (void)
Alert indication.
This Function can be used by any application to indicate an error condition. The function is blocking and does never return.
Definition at line 190 of file pal.c.
References ALERT_INDICATE, ALERT_INIT, and pal_timer_delay().
retval_t pal_init (void)
Initialization of PAL.
This function initializes the PAL. This includes selecting the proper system clock source, initializing the GPIOs, the interface to the transceiver, and the timers.
Returns:
MAC_SUCCESS if PAL initialization is successful, FAILURE otherwise
Definition at line 62 of file pal.c.
References gpio_init(), MAC_SUCCESS, mcu_clock_init(), timer_init(), trx_interface_init(), and TST_INIT.
retval_t pal_ps_get (ps_type_t ps_type, uint16_t start_addr, uint16_t length, void * value)
Get data from persistence storage.
Parameters:
[in] ps_type Persistence storage type
[in] start_addr Start offset within EEPROM
[in] length Number of bytes to read from EEPROM
[out] value Data from persistence storage
Returns:
MAC_SUCCESS if everything went OK else FAILURE
Definition at line 109 of file pal.c.
References EXTERN_EEPROM, FAILURE, INTERN_EEPROM, MAC_INVALID_PARAMETER, and MAC_SUCCESS.
retval_t pal_ps_set (uint16_t start_addr, uint16_t length, void * value)
Write data to persistence storage.
Parameters:
[in] start_addr Start address offset within EEPROM
[in] length Number of bytes to be written to EEPROM
[in] value Data to persistence storage
Returns:
MAC_SUCCESS if everything went OK else FAILURE
Definition at line 156 of file pal.c.
References FAILURE, and MAC_SUCCESS.
void pal_task (void)
Services timer and sio handler.
This function calls sio & timer handling functions.
Definition at line 82 of file pal.c.
References timer_service(), and usb_handler().
Variable Documentation
volatile uint16_t sys_time
This is the most significant part of the system time. The least one is timer1 (TCNT1) itself. Exported since input capture units might want to know about this value as well.
Definition at line 45 of file pal.c.
Referenced by gettime(), pal_trx_read_timestamp(), prog_ocr(), and timer_init().