AVR2025: IEEE 802.15.4 MAC Reference Manual
Microcontroller Wireless Solutions
pal_trx_access.c File Reference
Transceiver registers & Buffer accessing functions for AVR 8-Bit SPI based MCUs.
Typedefs
typedef void(* spi_done_handler_t)(void)
Enumerations
enum spi_state_t { SPI_IDLE, SPI_READ, SPI_WRITE }
Functions
void pal_trx_aes_wrrd (uint8_t addr, uint8_t *idata, uint8_t length)
uint8_t pal_trx_bit_read (uint8_t addr, uint8_t mask, uint8_t pos)
void pal_trx_bit_write (uint8_t reg_addr, uint8_t mask, uint8_t pos, uint8_t new_value)
void pal_trx_frame_read (uint8_t *data, uint8_t length)
void pal_trx_frame_write (uint8_t *data, uint8_t length)
uint8_t pal_trx_reg_read (uint8_t addr)
void pal_trx_reg_write (uint8_t addr, uint8_t data)
void pal_trx_sram_read (uint8_t addr, uint8_t *data, uint8_t length)
void pal_trx_sram_write (uint8_t addr, uint8_t *data, uint8_t length)
void trx_interface_init (void)
Detailed Description
Transceiver registers & Buffer accessing functions for AVR 8-Bit SPI based MCUs.
This file implements functions for reading and writing transceiver registers and transceiver buffer for AVR 8-Bit SPI based MCUs. The decision whether to use the implementation within this file is based on the presence of the macro PAL_USE_SPI_TRX, to be defined in the respective board's pal_config.h. Absence of this macro implies the TAL for the respective board supplies its own implementation of this API.
Id:
pal_trx_access.c 22250 2010-06-16 13:51:39Z sschneid
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Definition in file pal_trx_access.c.
Typedef Documentation
typedef void(* spi_done_handler_t)(void)
This is a typedef of the function which is called from SPI end
Definition at line 41 of file pal_trx_access.c.
Enumeration Type Documentation
enum spi_state_t
Enumerations used to identify SPI states
Definition at line 44 of file pal_trx_access.c.
Function Documentation
void pal_trx_aes_wrrd (uint8_t addr, uint8_t * idata, uint8_t length)
Writes and reads data into/from SRAM of the transceiver.
This function writes data into the SRAM of the transceiver and simultaneously reads the bytes.
Parameters:
addr Start address in the SRAM for the write operation
idata Pointer to the data written/read into/from SRAM
length Number of bytes written/read into/from SRAM
Definition at line 472 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, PAL_WAIT_500_NS, SPI_DUMMY_VALUE, SPI_WAIT, SS_HIGH, and SS_LOW.
uint8_t pal_trx_bit_read (uint8_t addr, uint8_t mask, uint8_t pos)
SPI transfer ISR.
Subregister read.
This function handles the non-blocking SPI transfer. Subregister read
Parameters:
addr offset of the register
mask bit mask of the subregister
pos bit position of the subregister
Returns:
value of the read bit(s)
Definition at line 316 of file pal_trx_access.c.
References pal_trx_reg_read().
void pal_trx_bit_write (uint8_t reg_addr, uint8_t mask, uint8_t pos, uint8_t new_value)
Subregister write.
Parameters:
[in] reg_addr Offset of the register
[in] mask Bit mask of the subregister
[in] pos Bit position of the subregister
[out] new_value Data, which is muxed into the register
Definition at line 336 of file pal_trx_access.c.
References pal_trx_reg_read(), and pal_trx_reg_write().
void pal_trx_frame_read (uint8_t * data, uint8_t length)
Reads frame buffer of the transceiver.
This function reads the frame buffer of the transceiver.
Parameters:
[out] data Pointer to the location to store frame
[in] length Number of bytes to be read from the frame buffer.
Definition at line 191 of file pal_trx_access.c.
References SPI_DUMMY_VALUE, SPI_WAIT, SS_HIGH, and SS_LOW.
void pal_trx_frame_write (uint8_t * data, uint8_t length)
Writes data into frame buffer of the transceiver.
This function writes data into the frame buffer of the transceiver
Parameters:
[in] data Pointer to data to be written into frame buffer
[in] length Number of bytes to be written into frame buffer
Definition at line 235 of file pal_trx_access.c.
References SPI_IRQ_ENABLE, SPI_WAIT, SS_HIGH, and SS_LOW.
uint8_t pal_trx_reg_read (uint8_t addr)
Reads current value from a transceiver register.
This function reads the current value from a transceiver register.
Parameters:
addr Specifies the address of the trx register from which the data shall be read
Returns:
value of the register read
Definition at line 143 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, SPI_DUMMY_VALUE, SPI_WAIT, SS_HIGH, and SS_LOW.
Referenced by pal_trx_bit_read(), and pal_trx_bit_write().
void pal_trx_reg_write (uint8_t addr, uint8_t data)
SPI done callback initialization.
Writes data into a transceiver register.
Writes data into a transceiver register
This function writes a value into transceiver register.
Parameters:
addr Address of the trx register
data Data to be written to trx register
Definition at line 101 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, SPI_WAIT, SS_HIGH, and SS_LOW.
Referenced by pal_trx_bit_write().
void pal_trx_sram_read (uint8_t addr, uint8_t * data, uint8_t length)
Reads data from SRAM of the transceiver.
This function reads from the SRAM of the transceiver
Parameters:
[in] addr Start address in SRAM for read operation
[out] data Pointer to the location where data stored
[in] length Number of bytes to be read from SRAM
Definition at line 412 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, PAL_WAIT_500_NS, SPI_DUMMY_VALUE, SPI_WAIT, SS_HIGH, and SS_LOW.
void pal_trx_sram_write (uint8_t addr, uint8_t * data, uint8_t length)
Writes data into SRAM of the transceiver.
This function writes data into the SRAM of the transceiver
Parameters:
addr Start address in the SRAM for the write operation
data Pointer to the data to be written into SRAM
length Number of bytes to be written into SRAM
Definition at line 361 of file pal_trx_access.c.
References ENTER_TRX_REGION, LEAVE_TRX_REGION, SPI_WAIT, SS_HIGH, and SS_LOW.
void trx_interface_init (void)
Initializes the transceiver interface.
This function initializes the transceiver interface.
Definition at line 75 of file pal_trx_access.c.
References TRX_INIT.
Referenced by pal_init().