AVR2025: IEEE 802.15.4 MAC Reference Manual
Microcontroller Wireless Solutions
pal_timer.c File Reference
Timer related functions for AVR 8-Bit MCUs.
Functions
static bool compare_time (uint32_t t1, uint32_t t2)
static uint32_t gettime (void)
void internal_timer_handler (void)
void pal_get_current_time (uint32_t *current_time)
bool pal_is_timer_running (uint8_t timer_id)
retval_t pal_start_high_priority_timer (uint8_t timer_id, uint16_t timer_count, FUNC_PTR timer_cb, void *param_cb)
retval_t pal_stop_high_priority_timer (uint8_t timer_id)
void pal_timer_delay (uint16_t delay)
void pal_timer_source_select (source_type_t source)
retval_t pal_timer_start (uint8_t timer_id, uint32_t timer_count, timeout_type_t timeout_type, FUNC_PTR timer_cb, void *param_cb)
retval_t pal_timer_stop (uint8_t timer_id)
static void prog_ocr (void)
static void start_absolute_timer (uint8_t timer_id, uint32_t point_in_time, FUNC_PTR handler_cb, void *parameter)
void TIMER1_COMPA_vect (void)
void TIMER1_COMPB_vect (void)
void TIMER1_OVF_vect (void)
void timer_init (void)
void timer_service (void)
Detailed Description
Timer related functions for AVR 8-Bit MCUs.
This file implements timer related functions for AVR 8-Bit MCUs.
Id:
pal_timer.c 20047 2010-01-28 11:59:48Z sschneid
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Definition in file pal_timer.c.
Function Documentation
static bool compare_time (uint32_t t1, uint32_t t2) [inline, static]
Compares two 32-bit time values.
This function compares two true 32-bit time values t1 and t2 and returns true if t1 is less than t2.
Parameters:
t1 Time
t2 Time
Returns:
true If t1 is less than t2 when MSBs are same, false otherwise.
Definition at line 100 of file pal_timer.c.
Referenced by prog_ocr(), and start_absolute_timer().
static uint32_t gettime (void) [inline, static]
Gets actual system time.
This function is called to get the system time
Returns:
Time in microseconds
Definition at line 733 of file pal_timer.c.
References sys_time.
Referenced by pal_get_current_time(), pal_timer_start(), and prog_ocr().
void internal_timer_handler (void)
Internal timer handler.
This function checks for expired timers and rearranges the running timer queue head and expired timer queue head and tail if there are any expired timers.
Definition at line 817 of file pal_timer.c.
References prog_ocr().
Referenced by pal_timer_stop(), start_absolute_timer(), and timer_service().
void pal_get_current_time (uint32_t * current_time)
Gets current time.
This function returns the current time.
Parameters:
[out] current_time Current system time
Definition at line 617 of file pal_timer.c.
References gettime().
bool pal_is_timer_running (uint8_t timer_id)
Checks if the timer with the requested timer identifier is running.
Checks if the timer of requested timer identifier is running.
Parameters:
timer_id Timer identifier
Returns:
true if timer with requested timer id is running,
false otherwise.
Definition at line 685 of file pal_timer.c.
retval_t pal_start_high_priority_timer (uint8_t timer_id, uint16_t timer_count, FUNC_PTR timer_cb, void * param_cb)
Starts high priority timer.
This function starts a high priority timer for the specified timeout.
Parameters:
timer_id Timer identifier
timer_count Timeout in microseconds
timer_cb Callback handler invoked upon timer expiry
param_cb Argument for the callback handler
Returns:
PAL_TMR_INVALID_ID if the identifier is undefined,
MAC_INVALID_PARAMETER if the callback function for this timer is NULL,
PAL_TMR_ALREADY_RUNNING if the timer is already running, or
MAC_SUCCESS if timer is started successfully.
Definition at line 285 of file pal_timer.c.
References ENTER_CRITICAL_REGION, LEAVE_CRITICAL_REGION, MAC_INVALID_PARAMETER, MAC_SUCCESS, PAL_TMR_ALREADY_RUNNING, and PAL_TMR_INVALID_ID.
retval_t pal_stop_high_priority_timer (uint8_t timer_id)
Stops a high priority timer.
This function stops a high priority timer.
Parameters:
timer_id Timer identifier
Returns:
PAL_TMR_NOT_RUNNING if the timer id does not match with the high priority timer register, or
MAC_SUCCESS otherwise.
Definition at line 522 of file pal_timer.c.
References ENTER_CRITICAL_REGION, LEAVE_CRITICAL_REGION, MAC_SUCCESS, and PAL_TMR_NOT_RUNNING.
void pal_timer_delay (uint16_t delay)
Performes blocking delay.
Generates blocking delay.
This functions performs a blocking delay of the specified time.
Parameters:
delay in microseconds
Definition at line 631 of file pal_timer.c.
References ENTER_CRITICAL_REGION, LEAVE_CRITICAL_REGION, and MIN_DELAY_VAL.
Referenced by pal_alert().
void pal_timer_source_select (source_type_t source)
Selects timer clock source.
This function selects the clock source of the timer.
Parameters:
source
TMR_CLK_SRC_DURING_TRX_SLEEP if clock source during sleep is to be selected, and
TMR_CLK_SRC_DURING_TRX_AWAKE if clock source while being awake is selected.
Definition at line 596 of file pal_timer.c.
References TIMER_SRC_DURING_TRX_AWAKE, TIMER_SRC_DURING_TRX_SLEEP, and TMR_CLK_SRC_DURING_TRX_SLEEP.
retval_t pal_timer_start (uint8_t timer_id, uint32_t timer_count, timeout_type_t timeout_type, FUNC_PTR timer_cb, void * param_cb)
Starts regular timer.
Start regular timer.
This function starts a regular timer and registers the corresponding callback function to handle the timeout event.
Parameters:
timer_id Timer identifier
timer_count Timeout in microseconds
timeout_type TIMEOUT_RELATIVE / TIMEOUT_ABSOLUTE
timer_cb Callback handler invoked upon timer expiry
param_cb Argument for the callback handler
Returns:
PAL_TMR_INVALID_ID if the timer identifier is undefined,
MAC_INVALID_PARAMETER if the callback function for this timer is NULL or timeout_type is invalid,
PAL_TMR_ALREADY_RUNNING if the timer is already running,
MAC_SUCCESS if timer is started, or
PAL_TMR_INVALID_TIMEOUT if timeout is not within the timeout range.
Definition at line 200 of file pal_timer.c.
References ADD_TIME, gettime(), MAC_INVALID_PARAMETER, MAC_SUCCESS, MAX_TIMEOUT, MIN_TIMEOUT, PAL_TMR_ALREADY_RUNNING, PAL_TMR_INVALID_ID, PAL_TMR_INVALID_TIMEOUT, start_absolute_timer(), SUB_TIME, TIMEOUT_ABSOLUTE, and TIMEOUT_RELATIVE.
retval_t pal_timer_stop (uint8_t timer_id)
Stops a running timer.
This function stops a running timer with the specified timer_id.
Parameters:
timer_id Timer identifier
Returns:
MAC_SUCCESS if the timer was stopped successfully,
PAL_TMR_NOT_RUNNING if the specified timer is not running,
PAL_TMR_INVALID_ID if the specified timer id is undefined.
Definition at line 360 of file pal_timer.c.
References ENTER_CRITICAL_REGION, internal_timer_handler(), LEAVE_CRITICAL_REGION, MAC_SUCCESS, PAL_TMR_INVALID_ID, PAL_TMR_NOT_RUNNING, and prog_ocr().
static void prog_ocr (void) [static]
Programs the output compare register OCR1A.
This function programs the OCR1A register with the timeout value of the timer present at the head of the running timer queue.
Definition at line 762 of file pal_timer.c.
References compare_time(), ENTER_CRITICAL_REGION, gettime(), LEAVE_CRITICAL_REGION, and sys_time.
Referenced by internal_timer_handler(), pal_timer_stop(), and start_absolute_timer().
static void start_absolute_timer (uint8_t timer_id, uint32_t point_in_time, FUNC_PTR handler_cb, void * parameter) [static]
Start a timer by setting its absolute expiration time.
This function starts a timer which should expire at the point_in_time value and upon timer expiry the function held by the handler is called.
Parameters:
timer_id Timer identifier
point_in_time Absolute expiration time in microseconds
handler_cb Function called upon timer expiry
parameter Parameter passed to the expired timer handler
Definition at line 877 of file pal_timer.c.
References compare_time(), ENTER_CRITICAL_REGION, internal_timer_handler(), LEAVE_CRITICAL_REGION, and prog_ocr().
Referenced by pal_timer_start().
void TIMER1_COMPA_vect (void)
Timer1 COMPA ISR.
This is the interrupt service routine for timer1 output compare match. It is triggered when a timer expires.
void TIMER1_COMPB_vect (void)
ISR for high priority timer, triggered by OCR1B.
This is the interrupt service routine for timer1.OCR1B output compare match. It is triggered when a high priority timer expires.
void TIMER1_OVF_vect (void)
Timer Overflow ISR.
This is the interrupt service routine for timer1 overflow. It is triggered every 65536 * 8 us, if clk to timer is 1MHz. The software portion of the system timer is incremented now.
void timer_init (void)
This function is called to initialize the timer module.
Definition at line 554 of file pal_timer.c.
References sys_time, and timer_init_non_generic().
Referenced by pal_init().
void timer_service (void)
Timer handling services.
This Function performs timer handling services. It calls functions which are responsible 1) to put the expired timer into the expired timer queue, and 2) to service expired timers and call the respective callback.
Definition at line 117 of file pal_timer.c.
References ENTER_CRITICAL_REGION, internal_timer_handler(), and LEAVE_CRITICAL_REGION.
Referenced by pal_task().